### ISSUE TITLE
README comments

### ISSUE THREAD

**Issue by FrankReh** [conradludgate/futures-buffered#3]
The README.md has "The is different".

Also has a second part to the Examples that perhaps requires some context for the casual reader to understand what it is showing.

```rust
use futures::future::join_all;

async fn foo(i: u32) -> u32 { i }

let futures = vec![foo(1), foo(2), foo(3)];

assert_eq!(join_all(futures).await, [1, 2, 3]);
```

Maybe this second example was meant to have a different `use` statement? As in the source doc:
```rust
use futures_buffered::join_all;
```

So having found join_all and try_join_all because of that second example, I wonder if perhaps this first line of the description could be changed to reflect that the crate offers more than one struct?

```
This project provides a single future structure: FuturesUnorderedBounded.
```

**Comment by conradludgate** [comment]
Yeah, thanks for bringing this up. The readme is probably quite out of date from what I first implemented. A lot of my documentation was also copied from futures, so it's possible some things are incorrect
